[tool.poetry]
name = "fruitsu"
version = "0.1.0"
description = "FruitSU - Tools for Apple Software Updates"
authors = ["Jevin Sweval <jevinsweval@gmail.com>"]

[tool.poe.tasks]
test = "pytest"
test-v = "pytest -vvvv"
test-vv = "pytest -vvvv --capture=tee-sys"

[tool.pytest.ini_options]
addopts = "--import-mode=append"
testpaths = [
    "tests",
]

[tool.poetry.dependencies]
python = "^3.9"
construct = "^2.10.66"
rich = "^10.1.0"
pretty-errors = "^1.2.19"
attrs = "^20.3.0"
fs = "^2.4.13"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
poethepoet = "^0.10.0"
pytest-clarity = "^0.3.0-alpha.0"
six = "^1.15.0"
pytest-pycharm = "^0.7.0"
pytest-randomly = "^3.7.0"
pytest-cov = "^2.11.1"
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
