[tool.poetry]
name = "fruitsu"
version = "0.1.0"
description = "FruitSU - Tools for Apple Software Updates"
authors = ["Jevin Sweval <jevinsweval@gmail.com>"]

[tool.poe.tasks]
test = "pytest"
test-v = "pytest -vvvv"
test-vv = "pytest -vvvv --capture=tee-sys"

[tool.pytest.ini_options]
addopts = "--import-mode=append"
testpaths = [
    "tests",
]

[tool.poetry.dependencies]
python = "^3.9"
construct = "^2.10.67"
rich = "^10.16.2"
pretty-errors = "^1.2.25"
attrs = "^20.3.0"
fs = "^2.4.15"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
poethepoet = "^0.10.0"
pytest-clarity = "^0.3.0a0"
six = "^1.16.0"
pytest-pycharm = "^0.7.0"
pytest-randomly = "^3.11.0"
pytest-cov = "^2.12.1"
mypy = "^0.812"

[build-system]
requires = ["poetry-core @ git+https://github.com/python-poetry/poetry-core.git@master"]
build-backend = "poetry.core.masonry.api"
